### ISSUE TITLE
Esbuild example with .html

### ISSUE THREAD

**Issue by posobin** [macaron-css/macaron#22]
Is there a full esbuild example? The one linked in the documentation [here](https://macaron.js.org/docs/examples/esbuild) emits an `index.js` and an `index.css` files. What's the suggested way to use these files in an html page? Should I just add a `<link src="index.css" rel="stylesheet" />` tag in the html? Would this always be single a compiled stylesheet if I have several styled components in different files?

**Comment by Mokshit06** [comment]
Hi, yes you're correct. Just add the link and script tags pointing to the output files (`dist/index.js` and `dist/index.css`) in the html file. The styles will always be compiled into a single css file, this is the way esbuild works.
