### ISSUE TITLE
[plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

### ISSUE THREAD

**Issue by dhanielsales** [macaron-css/macaron#32]
Hi there!

I got some problems using macaron-css with Solid JS + Vite. 

![image](https://user-images.githubusercontent.com/40248790/222993576-febf7b39-00b0-4af1-8eb9-034fd73b5223.png)

I only used the  `styled` function imported from `@macaron-css/solid` and got the issue from the photo above.

I created a codesandbox with the problem to make available here. I will try to debug the problem myself to try to contribute with the solution (In case it really is something macaron-css related)

Codesandbox: https://codesandbox.io/p/sandbox/hungry-hooks-d44xwu

**Comment by vaprdev** [comment]
@dhanielsales you need to reverse the order of arguments in your vite config to: 

```export default defineConfig({
  plugins: [macaronVitePlugin(), solidPlugin()],
  server: {
    port: 3000,
  },
  build: {
    target: 'esnext',
  },
});```

**Comment by Mokshit06** [comment]
@vaprdev Thanks! Closing this as I think it should be resolved.

**Comment by dhanielsales** [comment]
Ty guys, i'm sorry not reply at the time. The suggestion made by @vaprdev works well.
