### ISSUE TITLE
Forward prop types when styling a custom component

### ISSUE THREAD

**Issue by dugip** [macaron-css/macaron#37]
When you do:

```
const MyComponent = ({ customProp }: { customProp: Whatever }) => {...}

const StyledMyComponent = styled(MyComponent as any, {...});

<StyledMyComponent customProp={...} />
```

The prop `customProp` will throw a type error saying:

> Type '{ customProp: Whatever; }' is not assignable to type 'IntrinsicAttributes & ChildrenProp & RefAttributes<unknown>'.

**Comment by Mokshit06** [comment]
This seems to work for me. Can you try making a reproduction?
<img width="1265" alt="Screenshot 2023-04-08 at 11 05 20 PM" src="https://user-images.githubusercontent.com/50412128/230735186-c898ad78-8322-4271-8cfa-554a6e0e8bdf.png">

**Comment by dugip** [comment]
@Mokshit06 Seems like it still has something to do with `forwardRef`. Here's a repro repo:

https://stackblitz.com/edit/vitejs-vite-tfdmq5?file=src/App.tsx

**Comment by dugip** [comment]
@Mokshit06 I'm using the latest. In the repro you can also see I'm using the latest packages (_just_ created it.

**Comment by dugip** [comment]
![image](https://user-images.githubusercontent.com/128068361/230965834-70cab804-6dd8-4b51-8cf3-4a74cf472433.png)

**Comment by Mokshit06** [comment]
You haven't specified `value` prop in the type of `SelectItem`:
```tsx
const SelectItem = React.forwardRef(
  ({ children, ...props }: { children: React.ReactNode }, forwardedRef) => (
    <StyledItem {...props} ref={forwardedRef}>
      <RadixSelect.ItemText>{children}</RadixSelect.ItemText>
      <StyledItemIndicator>✓</StyledItemIndicator>
    </StyledItem>
  )
);
```

Adding that fixes the issue

**Comment by Mokshit06** [comment]
Closing this as I believe this is fixed. Feel free to open in case you face it again!
