### ISSUE TITLE
Prop "as" of styled components can be a component

### ISSUE THREAD

**Issue by dugip** [macaron-css/macaron#41]
From my tests, you can pass a component successfully to `as` (e.g. `<StyledBtn as={WhateverComponent} />`), but a type error is shown if you don't pass a string:

> Type 'WhateverComponent' is not assignable to type 'string'. ts(2322)

Types should be expanded to allow for more values here.

**Comment by Mokshit06** [comment]
I honestly don't see a great reason to add this. Polymorphic types like this make Typescript quite a lot slower and also are harder to ensure the correctness of. If you see yourself often using the `as` prop, maybe convert the `styled("button", styles)` to `recipe(styles)` and use it as `<WhateverComponent className={buttonStyle} />`?

**Comment by dugip** [comment]
Thanks, that helps 😄
