### ISSUE TITLE
Console warning when sourcemaps are enabled

### ISSUE THREAD

**Issue by sven-meyer-wetter-com** [macaron-css/macaron#42]
I'm currently experimenting with macaron in my vite project and really like it so far  💪

I'm having sourcemaps enabled via build -> sourcemap -> "hidden" option in vite.config.ts. When building for production, I getting a couple of (warning) messages in my console:

`Sourcemap is likely to be incorrect: a plugin (macaron-css-vite) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help`

This already fixed vanilla-extract issue is related I think:  https://github.com/vanilla-extract-css/vanilla-extract/issues/699

Can macaron suppress those warnings also?

To reproduce, see this Stackblitz example (modified react example from macarons homepage)

https://stackblitz.com/edit/macaron-css-macaron-pfbp8f

**Comment by Mokshit06** [comment]
Hey, thanks for reporting this. Will give it a look

**Comment by Mokshit06** [comment]
Should be fixed in the latest version of vite plugin!
