### ISSUE TITLE
Vite build watch doesn't work with Macaron

### ISSUE THREAD

**Issue by dugip** [macaron-css/macaron#44]
When using `vite build --watch`, the initial build works, but if you change the files to re-trigger a build, Macaron style generation will fail with the following error:

> [commonjs] Could not load /home/projects/vitejs-vite-ggwk6m/src/extracted_1bkv64o.css.ts: ENOENT: no such file or directory, open '/home/projects/vitejs-vite-ggwk6m/src/extracted_1bkv64o.css.ts'

Repro repo:

- https://stackblitz.com/edit/vitejs-vite-ggwk6m

Steps to test:

- Open a new terminal at the bottom
- Run `yarn build`
- Let initial build succeed
- Go to a tsx file and make an arbitrary change
- Save
- See the error in the terminal

**Comment by Pagebakers** [comment]
Same issues here with Vite, any known work around for this? Really like to get going with this lib but this is blocking me.

**Comment by Mokshit06** [comment]
Thanks for reporting this. I have been looking into what is causing it, and it seems to be a change in the internals of vite. I haven't been able to come up with a fix yet, but using a lower version of vite should fix it in the meanwhile

**Comment by Pagebakers** [comment]
I see, which version exactly? I'll downgrade for now.

**Comment by Mokshit06** [comment]
Hm yeah it looks like `vite build --watch` doesn't work, but if vite's HMR works if you are using a framework that makes use of that. Looks like an issue with how macaron resolves files – will try to find a fix for this

**Comment by Mokshit06** [comment]
Unfortunately I didn't get the time to work on it. Will try to see if I can fix it this week. If you want to try working on it, I would start by adding breakpoints/logs to the `resolveId` and `load` callbacks, and seeing when they don't resolve with watch mode. This probably has something to do with the `resolverCache`/`cssMap`/`idToPluginData`.

**Comment by Mokshit06** [comment]
This should be fixed in the latest version. The issue was that macaron was clearing the cache before every build, so every time you changed something, it would clear the cache in watch mode and then vite couldn't resolve the file.
