### ISSUE TITLE
Dynamic styling example in docs (still) doesn't work

### ISSUE THREAD

**Issue by aggggha** [macaron-css/macaron#49]
Hi! Sorry in advance if you find this confusing, my first ever issue on platform.
I came across your project from [this dicussion](https://github.com/stitchesjs/stitches/discussions/1149#discussioncomment-5398792_) and i love Stitches but sadly they're no longer maintained.

So, i don't find this issue #36 ([this one to be specific](https://github.com/macaron-css/macaron/issues/36#issuecomment-1500528664)) as a solved issue. Because you state that `style={assignInlineVars({ [colorVar]: val })}` was exported in v1.2.0. But still can't find that in import option and so the dynamic docs is still broken to me.

Maybe you have some tutorial or example for the usage of createVar() in action? or updated docs for this case. That would be great! Thanks!

**Comment by Mokshit06** [comment]
Hey! Sorry, just saw this. This is exported by macaron from `@macaron-css/core/dynamic` entrypoint (https://github.com/macaron-css/macaron/blob/main/packages/core/src/dynamic.ts). Can you try using this?

**Comment by aggggha** [comment]
Hello! Sorry just check in.
Sweet, it worked beautifully, thanks!
