### ISSUE TITLE
[Feature] Support @keyframes for animation

### ISSUE THREAD

**Issue by dhutaryan** [macaron-css/macaron#54]
Hello,

It seems there is not way to create and use `@keyframes` for animation. Could you take a look at this feature?

**Comment by Mokshit06** [comment]
Hi, `@macaron-css/core` uses vanilla-extract's `@vanilla-extract/css` as the core layer, on top of which macaron's bundler integrations and static extraction take over, so currently for quite a few base features the docs haven't been ported over to macaron.

Keyframes do exist though, and you can see the docs + examples over here https://vanilla-extract.style/documentation/api/keyframes/#keyframes
