### ISSUE TITLE
[Bug?] How to make createVar works?

### ISSUE THREAD

**Issue by dhutaryan** [macaron-css/macaron#55]
Hey, I saw all these issues https://github.com/macaron-css/macaron/issues/52 https://github.com/macaron-css/macaron/issues/49 https://github.com/macaron-css/macaron/issues/36

Example doesn't work properly and show an error
```
Warning: Unsupported style property var(--_1dagh370). Did you mean var(-_1dagh370)?
```

The I tried to import `assignInlineVars` but I couldn't
```
import { assignInlineVars } from "@macaron-css/core/dynamic";
```
<img width="712" alt="image" src="https://github.com/macaron-css/macaron/assets/22456467/81d535a3-de18-4638-8453-f615093aeb71">

Did I do something wrong?

```
"@macaron-css/core": "^1.2.0",
"@macaron-css/react": "^1.4.0",
"@macaron-css/vite": "^1.4.3",
```

**Comment by Mokshit06** [comment]
Hi @dhutaryan, which version of TS are you using? Older TS versions don't work with the exports condition, but the new ones do.

**Comment by dhutaryan** [comment]
I use `5.2.2`. Updated it to `5.4.5` but it didn't help. Could it be something with `tsconfig`?

**Comment by Mokshit06** [comment]
Is the `moduleResolution` in your `tsconfig` one of `node16`, `nodenext`, or `bundler`? If not try setting it to one of these, as only these ones support package.json `"exports"`

**Comment by dhutaryan** [comment]
`"moduleResolution": "bundler"` helped, thank you

**Comment by aryzing** [comment]
@Mokshit06 using `bundler`, yet the issue persists. These are project's versions,

```
"@macaron-css/core": "1.5.2",
"@macaron-css/react": "1.5.3",
"@macaron-css/vite": "1.5.1",
```
