### ISSUE TITLE
Can't bundle styles inside `node_modules`

### ISSUE THREAD

**Issue by alexamy** [macaron-css/macaron#67]
I am using `esbuild` plugin for bundling web app. For private packages inside our organization, we just ship TS code directly.

Because of [this specific line](https://github.com/macaron-css/macaron/blob/main/packages/esbuild/src/index.ts#L93), we can not use styles in our packages inside `node_modules`.

I think this issue can be resolved by adding boolean flag in bundler plugin config.

**Comment by Mokshit06** [comment]
Thanks for opening the issue! I'll follow up in the PR
