### ISSUE TITLE
Missing release on npmjs: @macaron-css/esbuild@1.6.0 

### ISSUE THREAD

**Issue by alexamy** [macaron-css/macaron#69]
Is npm publishing delayed or should be done manually?

v1.6.0 release:
https://github.com/macaron-css/macaron/releases/tag/v1.6.0

`@macaron-css/esbuild` is still 1.5.1 on npmjs: 
https://www.npmjs.com/package/@macaron-css/esbuild

**Comment by alexamy** [comment]
Hi @Mokshit06, please take a look.

**Comment by Mokshit06** [comment]
Published! Yeah it seems like my npm CLI credentials were expired so it didn't auto publish yesterday
