### ISSUE TITLE
Support css native kebab-case?

### ISSUE THREAD

**Issue by MrFoxPro** [macaron-css/macaron#7]
I know this library is using VE under the hood. But solid gives opportunity to define style properties as they are named in CSS, so, and as I found out it does work, but Typescript shows error:
![image](https://user-images.githubusercontent.com/17229619/202291252-0c363208-253d-4ae7-98c5-a5d1195ff2b1.png)

**Comment by Mokshit06** [comment]
I gave this some thought and have decided that I don't want to add this to macaron.
Supporting both camel case and kebab-case css in typescript would allow for same properties to exist more than once without error like `background-color` and `backgroundColor`.
Adding this would also mean to fork the type definitions from vanilla-extract and then rewrite them to support kebab-case at every point.
